version: '3.8'
services:
  app:
    image: data-entry
    ports:
      - "8082:8082"
    
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_management_4
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: school_management_4
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data: